;* * * * *  Small-C/Plus z88dk * * * * *
;  Version: 17448-f529c80-20210207
;
;	Reconstructed for z80 Module Assembler
;
;	Module compile time: Mon Jun 12 10:51:46 2023


	C_LINE	0,"textMode.c"

	MODULE	textMode_c


	INCLUDE "z80_crt0.hdr"


	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/compiler.h"
	C_LINE	4,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	17,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	26,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	35,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	40,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	45,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	50,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	55,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	60,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	65,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	70,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	75,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	80,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	85,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	89,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	90,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	91,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	93,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	94,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	95,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	101,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	106,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sys/types.h"
	C_LINE	11,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	13,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	14,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	15,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	17,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	18,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	19,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	21,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	22,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	23,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	25,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	26,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	27,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	29,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	30,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	31,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	33,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	34,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	35,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	37,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	38,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	40,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	41,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	43,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	44,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	49,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	52,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	54,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	55,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdint.h"
	C_LINE	5,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	150,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	151,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	152,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	153,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	154,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	155,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	156,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	157,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	158,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	159,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	160,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	161,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	162,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	163,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	164,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	165,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	166,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	167,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	168,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	169,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	170,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	171,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	172,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	179,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	180,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	181,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	182,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	183,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	191,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	195,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	198,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	201,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	202,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	205,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	206,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	209,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	210,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	212,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	213,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	214,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	215,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	227,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	228,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	230,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	232,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	239,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	247,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	248,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	249,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	251,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	252,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	276,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	277,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	278,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	279,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	280,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	281,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	288,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	289,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	290,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	292,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	293,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	294,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	305,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	306,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	307,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	309,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	310,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	336,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	341,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	349,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	350,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	352,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	353,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	368,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	400,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	401,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	403,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	404,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	406,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	407,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	409,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	410,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	412,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	414,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	415,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	416,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	417,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	419,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	420,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	421,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	422,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	424,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	425,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	426,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	427,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	428,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	440,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	441,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	443,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	444,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	446,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	447,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	449,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	450,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	452,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	454,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	455,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	456,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	457,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	459,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	460,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	6,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	19,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	21,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	23,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	26,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	28,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	30,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	34,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	35,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/interrupt.h"
	C_LINE	469,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	472,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	475,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	481,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	482,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	485,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/spectrum.h"
	C_LINE	13,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	34,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	37,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	38,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	39,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	40,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	41,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	42,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	44,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	45,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	51,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	52,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	53,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	56,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	78,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	83,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	96,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	97,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	98,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/fcntl.h"
	C_LINE	74,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	87,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	137,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	156,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	161,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	162,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	171,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	174,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	178,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	179,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	180,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	181,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	182,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	183,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	187,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	188,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	190,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	221,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	223,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	224,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	226,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	227,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	228,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	231,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	232,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	233,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	234,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	249,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	250,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	253,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	256,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	257,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	264,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	267,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	268,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	269,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	270,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	271,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	272,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	278,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	285,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	286,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	287,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	288,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	289,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	299,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	304,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	309,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	312,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	315,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	318,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	320,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	323,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	325,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	326,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	328,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	330,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	334,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	336,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	340,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	343,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	352,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	354,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	357,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	359,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	361,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdio.h"
	C_LINE	2,"textMode.c"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	27,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	28,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	30,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	31,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	34,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	35,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	38,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	39,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	43,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	44,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	47,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	48,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	52,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	53,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	92,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	93,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	69,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	70,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	71,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	72,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	73,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	74,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	75,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	76,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	77,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	78,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	79,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	131,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	132,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	133,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	134,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	135,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	136,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	137,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	138,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	139,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	140,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	141,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	142,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	143,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/malloc.h"
	C_LINE	107,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	120,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	121,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	126,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	127,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	128,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	129,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	130,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	131,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	143,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	144,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	145,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	146,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	150,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	151,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	153,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	154,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	179,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	187,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	195,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	203,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	211,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	212,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	216,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	217,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	221,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	222,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	226,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	227,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	236,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	237,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	239,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	254,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	255,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	256,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	269,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	273,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	274,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	275,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	276,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	277,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	278,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	293,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	295,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	296,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	312,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	313,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	318,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	321,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/stdlib.h"
	C_LINE	3,"textMode.c"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	7,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	8,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	9,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	10,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	11,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	12,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	13,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	14,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	15,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	16,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	17,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	18,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	19,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	20,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	21,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	22,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	23,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	24,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/ctype.h"
	C_LINE	4,"textMode.c"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	7,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	9,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	14,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	16,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	21,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	22,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	26,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	27,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	31,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	32,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	36,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	37,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	41,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	43,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	48,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	49,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	54,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	55,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	59,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	61,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	66,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	67,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	71,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	74,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	77,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	80,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	81,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	85,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	87,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	92,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	94,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	99,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	101,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	106,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	107,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	111,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	113,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	118,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	120,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	125,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	126,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	130,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	131,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	135,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	136,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	140,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	142,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	147,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	148,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	152,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	153,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	157,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	158,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	162,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	163,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	167,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	168,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	172,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	173,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	177,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	178,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	182,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	183,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	187,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	190,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	193,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	194,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	198,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	200,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	205,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	207,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	212,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	215,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	218,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	220,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	225,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	227,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	232,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	234,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	239,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	241,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	246,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	248,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	253,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	254,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	258,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	259,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	263,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	264,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	268,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	269,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	273,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	274,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	278,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	279,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	283,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	286,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	287,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	291,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	294,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	295,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	299,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	300,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	304,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	305,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	309,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	312,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	313,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	317,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	319,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	324,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	327,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	329,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	333,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	334,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	338,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	339,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	342,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	343,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	400,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	406,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	412,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	418,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/string.h"
	C_LINE	5,"textMode.c"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/dos.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	67,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	70,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	90,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	91,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	92,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	93,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	94,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	98,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	101,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	143,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/time.h"
	C_LINE	18,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/dos.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	17,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	18,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	19,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	20,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	21,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	24,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	25,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	26,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	27,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	28,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	29,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	30,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	33,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	36,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	37,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	41,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	42,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	46,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	47,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	51,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	54,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	57,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	60,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	61,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	62,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	63,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	66,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	69,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/sound.h"
	C_LINE	19,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/dos.h"
	C_LINE	21,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/dos.h"
	C_LINE	27,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/dos.h"
	C_LINE	23,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	57,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	79,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	80,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	83,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	86,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	87,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	102,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	105,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	106,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	119,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	63,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	66,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	69,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	71,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	72,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	73,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	74,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	75,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	76,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	77,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	78,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	80,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/X.h"
	C_LINE	77,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	82,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	112,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	119,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	149,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	159,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	167,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	177,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	205,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	210,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	225,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	226,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	228,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	243,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	244,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	246,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	261,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	263,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	284,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	285,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	287,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	301,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	302,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	305,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	314,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	325,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	338,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	348,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	357,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	370,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	379,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	389,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	399,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	408,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	420,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	434,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	444,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	453,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	468,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	478,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	488,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	499,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	509,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	522,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	534,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	546,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	561,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	573,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	583,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	595,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	632,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	657,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	0,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	691,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xlib.h"
	C_LINE	7,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	15,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	16,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	17,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	18,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	19,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	20,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	22,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	27,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	28,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	30,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	32,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	34,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	35,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	37,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	38,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	41,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	42,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	43,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	44,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	45,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	46,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	48,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	50,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	51,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	52,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	53,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	58,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	59,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	60,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	61,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	62,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	67,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	68,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	69,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	71,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	72,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	77,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	84,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	85,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	86,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	87,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	92,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	93,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	99,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/X11/Xz88dk.h"
	C_LINE	24,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	28,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	62,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	63,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	69,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	70,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	71,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	72,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	74,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	75,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	84,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	86,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	88,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	107,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	108,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	111,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	116,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	119,"E:\RetroComputers\Z88DK\lib\config\..\..\/include/conio.h"
	C_LINE	6,"textMode.c"
	C_LINE	0,"fpga.h"
	C_LINE	9,"textMode.c"
	C_LINE	0,"patterns.h"
	C_LINE	5,"patterns.h"
	SECTION	data_compiler
._ASCII
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	32
	defb	32
	defb	32
	defb	32
	defb	32
	defb	0
	defb	32
	defb	0
	defb	80
	defb	80
	defb	80
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	80
	defb	80
	defb	248
	defb	80
	defb	248
	defb	80
	defb	80
	defb	0
	defb	32
	defb	120
	defb	160
	defb	112
	defb	40
	defb	240
	defb	32
	defb	0
	defb	192
	defb	200
	defb	16
	defb	32
	defb	64
	defb	152
	defb	24
	defb	0
	defb	64
	defb	160
	defb	160
	defb	64
	defb	168
	defb	144
	defb	104
	defb	0
	defb	32
	defb	32
	defb	32
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	32
	defb	64
	defb	128
	defb	128
	defb	128
	defb	64
	defb	32
	defb	0
	defb	32
	defb	16
	defb	8
	defb	8
	defb	8
	defb	16
	defb	32
	defb	0
	defb	32
	defb	168
	defb	112
	defb	32
	defb	112
	defb	168
	defb	32
	defb	0
	defb	0
	defb	32
	defb	32
	defb	248
	defb	32
	defb	32
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	32
	defb	32
	defb	64
	defb	0
	defb	0
	defb	0
	defb	0
	defb	248
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	32
	defb	0
	defb	0
	defb	8
	defb	16
	defb	32
	defb	64
	defb	128
	defb	0
	defb	0
	defb	112
	defb	136
	defb	152
	defb	168
	defb	200
	defb	136
	defb	112
	defb	0
	defb	32
	defb	96
	defb	32
	defb	32
	defb	32
	defb	32
	defb	112
	defb	0
	defb	112
	defb	136
	defb	8
	defb	48
	defb	64
	defb	128
	defb	248
	defb	0
	defb	248
	defb	8
	defb	16
	defb	48
	defb	8
	defb	136
	defb	112
	defb	0
	defb	16
	defb	48
	defb	80
	defb	144
	defb	248
	defb	16
	defb	16
	defb	0
	defb	248
	defb	128
	defb	240
	defb	8
	defb	8
	defb	136
	defb	112
	defb	0
	defb	56
	defb	64
	defb	128
	defb	240
	defb	136
	defb	136
	defb	112
	defb	0
	defb	248
	defb	8
	defb	16
	defb	32
	defb	64
	defb	64
	defb	64
	defb	0
	defb	112
	defb	136
	defb	136
	defb	112
	defb	136
	defb	136
	defb	112
	defb	0
	defb	112
	defb	136
	defb	136
	defb	120
	defb	8
	defb	16
	defb	224
	defb	0
	defb	0
	defb	0
	defb	32
	defb	0
	defb	32
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	32
	defb	0
	defb	32
	defb	32
	defb	64
	defb	0
	defb	16
	defb	32
	defb	64
	defb	128
	defb	64
	defb	32
	defb	16
	defb	0
	defb	0
	defb	0
	defb	248
	defb	0
	defb	248
	defb	0
	defb	0
	defb	0
	defb	64
	defb	32
	defb	16
	defb	8
	defb	16
	defb	32
	defb	64
	defb	0
	defb	112
	defb	136
	defb	16
	defb	32
	defb	32
	defb	0
	defb	32
	defb	0
	defb	112
	defb	136
	defb	168
	defb	184
	defb	176
	defb	128
	defb	120
	defb	0
	defb	32
	defb	80
	defb	136
	defb	136
	defb	248
	defb	136
	defb	136
	defb	0
	defb	240
	defb	136
	defb	136
	defb	240
	defb	136
	defb	136
	defb	240
	defb	0
	defb	112
	defb	136
	defb	128
	defb	128
	defb	128
	defb	136
	defb	112
	defb	0
	defb	240
	defb	136
	defb	136
	defb	136
	defb	136
	defb	136
	defb	240
	defb	0
	defb	248
	defb	128
	defb	128
	defb	240
	defb	128
	defb	128
	defb	248
	defb	0
	defb	248
	defb	128
	defb	128
	defb	240
	defb	128
	defb	128
	defb	128
	defb	0
	defb	120
	defb	128
	defb	128
	defb	128
	defb	152
	defb	136
	defb	120
	defb	0
	defb	136
	defb	136
	defb	136
	defb	248
	defb	136
	defb	136
	defb	136
	defb	0
	defb	112
	defb	32
	defb	32
	defb	32
	defb	32
	defb	32
	defb	112
	defb	0
	defb	8
	defb	8
	defb	8
	defb	8
	defb	8
	defb	136
	defb	112
	defb	0
	defb	136
	defb	144
	defb	160
	defb	192
	defb	160
	defb	144
	defb	136
	defb	0
	defb	128
	defb	128
	defb	128
	defb	128
	defb	128
	defb	128
	defb	248
	defb	0
	defb	136
	defb	216
	defb	168
	defb	168
	defb	136
	defb	136
	defb	136
	defb	0
	defb	136
	defb	136
	defb	200
	defb	168
	defb	152
	defb	136
	defb	136
	defb	0
	defb	112
	defb	136
	defb	136
	defb	136
	defb	136
	defb	136
	defb	112
	defb	0
	defb	240
	defb	136
	defb	136
	defb	240
	defb	128
	defb	128
	defb	128
	defb	0
	defb	112
	defb	136
	defb	136
	defb	136
	defb	168
	defb	144
	defb	104
	defb	0
	defb	240
	defb	136
	defb	136
	defb	240
	defb	160
	defb	144
	defb	136
	defb	0
	defb	112
	defb	136
	defb	128
	defb	112
	defb	8
	defb	136
	defb	112
	defb	0
	defb	248
	defb	32
	defb	32
	defb	32
	defb	32
	defb	32
	defb	32
	defb	0
	defb	136
	defb	136
	defb	136
	defb	136
	defb	136
	defb	136
	defb	112
	defb	0
	defb	136
	defb	136
	defb	136
	defb	136
	defb	136
	defb	80
	defb	32
	defb	0
	defb	136
	defb	136
	defb	136
	defb	168
	defb	168
	defb	216
	defb	136
	defb	0
	defb	136
	defb	136
	defb	80
	defb	32
	defb	80
	defb	136
	defb	136
	defb	0
	defb	136
	defb	136
	defb	80
	defb	32
	defb	32
	defb	32
	defb	32
	defb	0
	defb	248
	defb	8
	defb	16
	defb	32
	defb	64
	defb	128
	defb	248
	defb	0
	defb	120
	defb	64
	defb	64
	defb	64
	defb	64
	defb	64
	defb	120
	defb	0
	defb	0
	defb	128
	defb	64
	defb	32
	defb	16
	defb	8
	defb	0
	defb	0
	defb	240
	defb	16
	defb	16
	defb	16
	defb	16
	defb	16
	defb	240
	defb	0
	defb	0
	defb	0
	defb	32
	defb	80
	defb	136
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	248
	defb	64
	defb	32
	defb	16
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	96
	defb	16
	defb	112
	defb	144
	defb	104
	defb	0
	defb	128
	defb	128
	defb	176
	defb	200
	defb	136
	defb	200
	defb	176
	defb	0
	defb	0
	defb	0
	defb	112
	defb	136
	defb	128
	defb	136
	defb	112
	defb	0
	defb	8
	defb	8
	defb	120
	defb	136
	defb	136
	defb	136
	defb	120
	defb	0
	defb	0
	defb	0
	defb	112
	defb	136
	defb	248
	defb	128
	defb	120
	defb	0
	defb	48
	defb	72
	defb	64
	defb	240
	defb	64
	defb	64
	defb	64
	defb	0
	defb	0
	defb	0
	defb	104
	defb	152
	defb	152
	defb	104
	defb	8
	defb	240
	defb	128
	defb	128
	defb	176
	defb	200
	defb	136
	defb	136
	defb	136
	defb	0
	defb	32
	defb	0
	defb	96
	defb	32
	defb	32
	defb	32
	defb	112
	defb	0
	defb	8
	defb	0
	defb	24
	defb	8
	defb	8
	defb	8
	defb	72
	defb	48
	defb	128
	defb	128
	defb	136
	defb	144
	defb	160
	defb	208
	defb	136
	defb	0
	defb	48
	defb	16
	defb	16
	defb	16
	defb	16
	defb	16
	defb	56
	defb	0
	defb	0
	defb	0
	defb	80
	defb	248
	defb	168
	defb	168
	defb	168
	defb	0
	defb	0
	defb	0
	defb	176
	defb	200
	defb	136
	defb	136
	defb	136
	defb	0
	defb	0
	defb	0
	defb	112
	defb	136
	defb	136
	defb	136
	defb	112
	defb	0
	defb	0
	defb	0
	defb	176
	defb	200
	defb	200
	defb	176
	defb	128
	defb	128
	defb	0
	defb	0
	defb	104
	defb	152
	defb	152
	defb	104
	defb	8
	defb	8
	defb	0
	defb	0
	defb	176
	defb	200
	defb	128
	defb	128
	defb	128
	defb	0
	defb	0
	defb	0
	defb	112
	defb	128
	defb	112
	defb	8
	defb	240
	defb	0
	defb	64
	defb	64
	defb	240
	defb	64
	defb	64
	defb	72
	defb	48
	defb	0
	defb	0
	defb	0
	defb	136
	defb	136
	defb	136
	defb	152
	defb	104
	defb	0
	defb	0
	defb	0
	defb	136
	defb	136
	defb	136
	defb	80
	defb	32
	defb	0
	defb	0
	defb	0
	defb	136
	defb	168
	defb	168
	defb	168
	defb	80
	defb	0
	defb	0
	defb	0
	defb	136
	defb	80
	defb	32
	defb	80
	defb	136
	defb	0
	defb	0
	defb	0
	defb	136
	defb	136
	defb	152
	defb	104
	defb	8
	defb	112
	defb	0
	defb	0
	defb	248
	defb	16
	defb	32
	defb	64
	defb	248
	defb	0
	defb	56
	defb	64
	defb	32
	defb	192
	defb	32
	defb	64
	defb	56
	defb	0
	defb	64
	defb	32
	defb	16
	defb	8
	defb	16
	defb	32
	defb	64
	defb	0
	defb	224
	defb	16
	defb	32
	defb	24
	defb	32
	defb	16
	defb	224
	defb	0
	defb	64
	defb	168
	defb	16
	defb	0
	defb	0
	defb	0
	defb	0
	defb	0
	defb	168
	defb	80
	defb	168
	defb	80
	defb	168
	defb	80
	defb	168
	defb	0
	SECTION	code_compiler
	C_LINE	10,"textMode.c"
	C_LINE	13,"textMode.c"
	C_LINE	14,"textMode.c"
	C_LINE	15,"textMode.c"
	C_LINE	16,"textMode.c"
	C_LINE	17,"textMode.c"
	C_LINE	18,"textMode.c"
	C_LINE	21,"textMode.c"
	SECTION	data_compiler
._textModeInit
	defb	0
	defb	208
	defb	2
	defb	0
	defb	0
	defb	32
	defb	0
	defb	245
	SECTION	code_compiler
	C_LINE	24,"textMode.c"
	C_LINE	27,"textMode.c"

; Function main flags 0x00000000 __stdc 
; int main()
	C_LINE	27,"textMode.c::main"
._main
	ld	hl,136	;const
	push	hl
	ld	hl,64	;const
	push	hl
	call	_writeUlaReg
	pop	bc
	pop	bc
	call	_vdp_setTextMode
	ld	hl,_ASCII
	push	hl
	ld	hl,768	;const
	push	hl
	ld	hl,0	;const
	push	hl
	call	_vdp_writeMemBlk
	pop	bc
	pop	bc
	pop	bc
	ld	de,_testMsg
	ld	hl,i_1+0
	push	de
	xor	a
.i_4
	cp	(hl)
	ldi
	jr	nz,i_4
	pop	hl
	ld	hl,_testMsg
	push	hl
	call	strlen
	push	hl
	ld	hl,2049	;const
	push	hl
	call	_vdp_writeMemBlk
	pop	bc
	pop	bc
	pop	bc
	ret


	C_LINE	41,"textMode.c::main"

; Function vdp_setTextMode flags 0x00000200 __smallc 
; void vdp_setTextMode()
	C_LINE	41,"textMode.c::vdp_setTextMode"
._vdp_setTextMode
	dec	sp
	ld	hl,0	;const
	add	hl,sp
	push	hl
	ld	a,(hl)
	pop	de
	ld	(de),a
	ld	l,a
	ld	h,0
	jp	i_7
.i_5
	ld	hl,0	;const
	add	hl,sp
	inc	(hl)
.i_7
	pop	hl
	push	hl
	ld	h,0
	ld	a,l
	sub	8
	jp	nc,i_6
	pop	hl
	push	hl
	ld	h,0
	push	hl
	ld	de,_textModeInit
	ld	hl,2	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	add	hl,de
	ld	l,(hl)
	ld	h,0
	push	hl
	call	_vdp_writeReg
	pop	bc
	pop	bc
	jp	i_5
.i_6
	inc	sp
	ret


	C_LINE	49,"textMode.c::vdp_setTextMode"

; Function vdp_writeReg flags 0x00000200 __smallc 
; void vdp_writeReg(unsigned char reg, int val)
; parameter 'int val' at sp+2 size(2)
; parameter 'unsigned char reg' at sp+4 size(1)
	C_LINE	49,"textMode.c::vdp_writeReg"
._vdp_writeReg
	ld	hl,4	;const
	add	hl,sp
	push	hl
	ld	a,(hl)
	and	+(7 % 256)
	ld	l,a
	ld	h,0
	set	7,l
	pop	de
	ld	a,l
	ld	(de),a
	ld	hl,161	;const
	push	hl
	ld	hl,6	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	push	hl
	call	outp_callee
	ld	hl,161	;const
	push	hl
	ld	hl,4	;const
	add	hl,sp
	call	l_gint	;
	push	hl
	call	outp_callee
	ret


	C_LINE	57,"textMode.c::vdp_writeReg"

; Function vdp_getStat flags 0x00000200 __smallc 
; unsigned char vdp_getStat()
	C_LINE	57,"textMode.c::vdp_getStat"
._vdp_getStat
	ld	hl,161	;const
	call	inp
	ld	h,0
	ret


	C_LINE	61,"textMode.c::vdp_getStat"

; Function vdp_writeMemBlk flags 0x00000200 __smallc 
; void vdp_writeMemBlk(unsigned char * data, unsigned int len, unsigned int adr)
; parameter 'unsigned int adr' at sp+2 size(2)
; parameter 'unsigned int len' at sp+4 size(2)
; parameter 'unsigned char * data' at sp+6 size(2)
	C_LINE	61,"textMode.c::vdp_writeMemBlk"
._vdp_writeMemBlk
	push	bc
	dec	sp
	ld	hl,i_1+14
	push	hl
	ld	hl,9	;const
	add	hl,sp
	call	l_gint	;
	push	hl
	ld	a,2
	call	printf
	pop	bc
	pop	bc
	ld	hl,i_1+32
	push	hl
	ld	hl,11	;const
	call	l_gintspsp	;
	ld	hl,9	;const
	add	hl,sp
	call	l_gint	;
	push	hl
	ld	a,3
	call	printf
	pop	bc
	pop	bc
	pop	bc
	ld	hl,5	;const
	add	hl,sp
	push	hl
	call	l_gint	;
	ld	de,16383
	call	l_and
	set	6,h
	pop	de
	call	l_pint
	ld	hl,2	;const
	add	hl,sp
	ex	de,hl
	ld	hl,5	;const
	add	hl,sp
	call	l_gint	;
	ld	a,l
	ld	(de),a
	ld	hl,161	;const
	push	hl
	ld	hl,4	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	push	hl
	call	_vdp_writeReg
	pop	bc
	pop	bc
	ld	hl,2	;const
	add	hl,sp
	push	hl
	ld	hl,7	;const
	add	hl,sp
	call	l_gint	;
	ld	l,h
	pop	de
	ld	a,l
	ld	(de),a
	ld	hl,161	;const
	push	hl
	ld	hl,4	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	push	hl
	call	_vdp_writeReg
	pop	bc
	pop	bc
	ld	hl,0	;const
	pop	bc
	push	hl
	jp	i_10
.i_8
	pop	hl
	inc	hl
	push	hl
.i_10
	pop	de
	push	de
	ld	hl,7	;const
	add	hl,sp
	call	l_gint	;
	ex	de,hl
	and	a
	sbc	hl,de
	jp	nc,i_9
	ld	hl,160	;const
	push	hl
	ld	hl,11	;const
	add	hl,sp
	call	l_gint	;
	ld	l,(hl)
	ld	h,0
	push	hl
	call	outp_callee
	ld	hl,9	;const
	add	hl,sp
	inc	(hl)
	ld	a,(hl)
	inc	hl
	jr	nz,ASMPC+3
	inc	(hl)
	ld	h,(hl)
	ld	l,a
	dec	hl
	jp	i_8
.i_9
	inc	sp
	pop	bc
	ret


	C_LINE	81,"textMode.c::vdp_writeMemBlk"

; Function vdp_getMemBlk flags 0x00000200 __smallc 
; void vdp_getMemBlk(unsigned int adr, unsigned int len, unsigned char * data)
; parameter 'unsigned char * data' at sp+2 size(2)
; parameter 'unsigned int len' at sp+4 size(2)
; parameter 'unsigned int adr' at sp+6 size(2)
	C_LINE	81,"textMode.c::vdp_getMemBlk"
._vdp_getMemBlk
	push	bc
	dec	sp
	ld	hl,9	;const
	add	hl,sp
	push	hl
	call	l_gint	;
	ld	de,16383
	call	l_and
	set	6,h
	pop	de
	call	l_pint
	ld	hl,2	;const
	add	hl,sp
	ex	de,hl
	ld	hl,9	;const
	add	hl,sp
	call	l_gint	;
	ld	a,l
	ld	(de),a
	ld	hl,161	;const
	push	hl
	ld	hl,4	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	push	hl
	call	_vdp_writeReg
	pop	bc
	pop	bc
	ld	hl,2	;const
	add	hl,sp
	push	hl
	ld	hl,11	;const
	add	hl,sp
	call	l_gint	;
	ld	l,h
	pop	de
	ld	a,l
	ld	(de),a
	ld	hl,161	;const
	push	hl
	ld	hl,4	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	push	hl
	call	_vdp_writeReg
	pop	bc
	pop	bc
	ld	hl,0	;const
	pop	bc
	push	hl
	jp	i_13
.i_11
	pop	hl
	inc	hl
	push	hl
.i_13
	pop	de
	push	de
	ld	hl,7	;const
	add	hl,sp
	call	l_gint	;
	ex	de,hl
	and	a
	sbc	hl,de
	jp	nc,i_12
	ld	hl,5	;const
	call	l_gintspsp	;
	ld	hl,160	;const
	call	inp
	pop	de
	ld	a,l
	ld	(de),a
	ld	hl,5	;const
	add	hl,sp
	inc	(hl)
	ld	a,(hl)
	inc	hl
	jr	nz,ASMPC+3
	inc	(hl)
	ld	h,(hl)
	ld	l,a
	dec	hl
	jp	i_11
.i_12
	inc	sp
	pop	bc
	ret


	C_LINE	98,"textMode.c::vdp_getMemBlk"

; Function writeUlaReg flags 0x00000200 __smallc 
; void writeUlaReg(unsigned char reg, int val)
; parameter 'int val' at sp+2 size(2)
; parameter 'unsigned char reg' at sp+4 size(1)
	C_LINE	98,"textMode.c::writeUlaReg"
._writeUlaReg
	ld	hl,48955	;const
	push	hl
	ld	hl,6	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	push	hl
	call	outp_callee
	ld	hl,65339	;const
	push	hl
	ld	hl,4	;const
	add	hl,sp
	call	l_gint	;
	push	hl
	call	outp_callee
	ret


	SECTION	rodata_compiler
.i_1
	defm	"Hello, world!"
	defb	0

	defm	"writing %u bytes "
	defb	0

	defm	"from %u to %u"
	defb	10

	defm	""
	defb	0


; --- Start of Static Variables ---

	SECTION	bss_compiler
._testMsg	defs	80
	SECTION	code_compiler


; --- Start of Scope Defns ---

	GLOBAL	zx_128mode
	GLOBAL	zx_floatingbus
	GLOBAL	zx_issue3
	GLOBAL	zx_type
	GLOBAL	zx_model
	GLOBAL	zx_basic_length
	GLOBAL	zx_var_length
	GLOBAL	zx_printer
	GLOBAL	zx_soundchip
	GLOBAL	zx_timexsound
	GLOBAL	zx_fullerstick
	GLOBAL	zx_kempstonmouse
	GLOBAL	zx_kempston
	GLOBAL	zx_iss_stick
	GLOBAL	zx_mb02
	GLOBAL	zx_multiface
	GLOBAL	zx_disciple
	GLOBAL	zx_plus3fdc
	GLOBAL	zx_zxmmc
	GLOBAL	zx_extsys
	GLOBAL	zx_basemem
	GLOBAL	zx_break
	GLOBAL	zx_ulaplus
	GLOBAL	ula_plus_mode
	GLOBAL	ula_normal_mode
	GLOBAL	ula_sync
	GLOBAL	ulaplus_set
	GLOBAL	ulaplus_get
	GLOBAL	zx_syntax
	GLOBAL	zx_goto
	GLOBAL	zx_line
	GLOBAL	zx_getstr
	GLOBAL	zx_setstr
	GLOBAL	zx_getint
	GLOBAL	zx_setint
	GLOBAL	zx_getfloat
	GLOBAL	zx_setfloat
	GLOBAL	zx_getstr_callee
	GLOBAL	zx_setstr_callee
	GLOBAL	zx_setint_callee
	GLOBAL	zx_setfloat_callee
	GLOBAL	zx_lprintc
	GLOBAL	zx_hardcopy
	GLOBAL	zx_print_buf
	GLOBAL	zx_print_row
	GLOBAL	tape_save
	GLOBAL	tape_save_block
	GLOBAL	tape_load_block
	GLOBAL	tape_save_block_callee
	GLOBAL	tape_load_block_callee
	GLOBAL	in_JoyFuller
	GLOBAL	in_JoyKempston
	GLOBAL	in_JoySinclair1
	GLOBAL	in_JoySinclair2
	GLOBAL	in_JoyTimex1
	GLOBAL	in_JoyTimex2
	GLOBAL	in_MouseAMXInit
	GLOBAL	in_MouseAMX
	GLOBAL	in_MouseAMXSetPos
	GLOBAL	in_MouseAMXInit_callee
	GLOBAL	in_MouseAMX_callee
	GLOBAL	in_MouseAMXSetPos_callee
	GLOBAL	in_MouseKempInit
	GLOBAL	in_MouseKemp
	GLOBAL	in_MouseKempSetPos
	GLOBAL	in_MouseKemp_callee
	GLOBAL	in_MouseKempSetPos_callee
	GLOBAL	zx_border
	GLOBAL	zx_colour
	GLOBAL	zx_attr
	GLOBAL	zx_screenstr
	GLOBAL	zx_attr_callee
	GLOBAL	zx_screenstr_callee
	GLOBAL	zx_printf
	GLOBAL	zx_cxy2saddr
	GLOBAL	zx_cy2saddr
	GLOBAL	zx_pxy2saddr
	GLOBAL	zx_py2saddr
	GLOBAL	zx_saddr2cx
	GLOBAL	zx_saddr2cy
	GLOBAL	zx_saddr2px
	GLOBAL	zx_saddr2py
	GLOBAL	zx_saddr2aaddr
	GLOBAL	zx_saddrcdown
	GLOBAL	zx_saddrcleft
	GLOBAL	zx_saddrcright
	GLOBAL	zx_saddrcup
	GLOBAL	zx_saddrpdown
	GLOBAL	zx_saddrpleft
	GLOBAL	zx_saddrpright
	GLOBAL	zx_saddrpup
	GLOBAL	zx_cxy2saddr_callee
	GLOBAL	zx_pxy2saddr_callee
	GLOBAL	zx_saddr2px_callee
	GLOBAL	zx_saddrpleft_callee
	GLOBAL	zx_saddrpright_callee
	GLOBAL	zx_cxy2aaddr
	GLOBAL	zx_cy2aaddr
	GLOBAL	zx_pxy2aaddr
	GLOBAL	zx_py2aaddr
	GLOBAL	zx_aaddr2cx
	GLOBAL	zx_aaddr2cy
	GLOBAL	zx_aaddr2px
	GLOBAL	zx_aaddr2py
	GLOBAL	zx_aaddr2saddr
	GLOBAL	zx_aaddrcdown
	GLOBAL	zx_aaddrcleft
	GLOBAL	zx_aaddrcright
	GLOBAL	zx_aaddrcup
	GLOBAL	zx_cxy2aaddr_callee
	GLOBAL	zx_pxy2aaddr_callee
	GLOBAL	im1_init
	GLOBAL	im1_install_isr
	GLOBAL	im1_uninstall_isr
	GLOBAL	nmi_init
	GLOBAL	nmi_install_isr
	GLOBAL	nmi_uninstall_isr
	GLOBAL	tick_count_isr
	GLOBAL	_tick_count
	GLOBAL	zx_im2_init
	GLOBAL	add_raster_int
	GLOBAL	zxgetfname
	GLOBAL	zxgetfname2
	GLOBAL	open
	GLOBAL	creat
	GLOBAL	close
	GLOBAL	read
	GLOBAL	write
	GLOBAL	lseek
	GLOBAL	readbyte
	GLOBAL	writebyte
	GLOBAL	getcwd
	GLOBAL	chdir
	GLOBAL	getwd
	GLOBAL	rmdir
	GLOBAL	_RND_BLOCKSIZE
	GLOBAL	rnd_loadblock
	GLOBAL	rnd_saveblock
	GLOBAL	rnd_erase
	GLOBAL	__FOPEN_MAX
	GLOBAL	__sgoioblk
	GLOBAL	__sgoioblk_end
	GLOBAL	fopen_zsock
	GLOBAL	fileno
	GLOBAL	fopen
	GLOBAL	freopen
	GLOBAL	fdopen
	GLOBAL	_freopen1
	GLOBAL	fmemopen
	GLOBAL	funopen
	GLOBAL	fclose
	GLOBAL	fflush
	GLOBAL	closeall
	GLOBAL	fgets
	GLOBAL	fputs
	GLOBAL	fputc
	GLOBAL	fputs_callee
	GLOBAL	fputc_callee
	GLOBAL	fgetc
	GLOBAL	ungetc
	GLOBAL	feof
	GLOBAL	ferror
	GLOBAL	puts
	GLOBAL	ftell
	GLOBAL	fgetpos
	GLOBAL	fseek
	GLOBAL	fread
	GLOBAL	fwrite
	GLOBAL	gets
	GLOBAL	printf
	GLOBAL	fprintf
	GLOBAL	sprintf
	GLOBAL	snprintf
	GLOBAL	vfprintf
	GLOBAL	vsnprintf
	GLOBAL	printn
	GLOBAL	scanf
	GLOBAL	fscanf
	GLOBAL	sscanf
	GLOBAL	vfscanf
	GLOBAL	vsscanf
	GLOBAL	getarg
	GLOBAL	fchkstd
	GLOBAL	fgetc_cons
	GLOBAL	fgetc_cons_inkey
	GLOBAL	fputc_cons
	GLOBAL	fgets_cons
	GLOBAL	puts_cons
	GLOBAL	fabandon
	GLOBAL	fdtell
	GLOBAL	fdgetpos
	GLOBAL	rename
	GLOBAL	remove
	GLOBAL	getk
	GLOBAL	getk_inkey
	GLOBAL	printk
	GLOBAL	perror
	GLOBAL	set_fputc_cons
	GLOBAL	fputc_cons_native
	GLOBAL	fputc_cons_generic
	GLOBAL	fputc_cons_ansi
	GLOBAL	atoi
	GLOBAL	atol
	GLOBAL	itoa
	GLOBAL	itoa_callee
	GLOBAL	ltoa
	GLOBAL	ltoa_callee
	GLOBAL	strtol
	GLOBAL	strtol_callee
	GLOBAL	strtoul
	GLOBAL	strtoul_callee
	GLOBAL	ultoa
	GLOBAL	ultoa_callee
	GLOBAL	utoa
	GLOBAL	utoa_callee
	GLOBAL	rand
	GLOBAL	srand
	GLOBAL	mallinit
	GLOBAL	sbrk
	GLOBAL	sbrk_callee
	GLOBAL	calloc
	GLOBAL	calloc_callee
	GLOBAL	free
	GLOBAL	malloc
	GLOBAL	realloc
	GLOBAL	realloc_callee
	GLOBAL	mallinfo
	GLOBAL	mallinfo_callee
	GLOBAL	HeapCreate
	GLOBAL	HeapSbrk
	GLOBAL	HeapSbrk_callee
	GLOBAL	HeapCalloc
	GLOBAL	HeapCalloc_callee
	GLOBAL	HeapFree
	GLOBAL	HeapFree_callee
	GLOBAL	HeapAlloc
	GLOBAL	HeapAlloc_callee
	GLOBAL	HeapRealloc
	GLOBAL	HeapRealloc_callee
	GLOBAL	HeapInfo
	GLOBAL	HeapInfo_callee
	GLOBAL	exit
	GLOBAL	atexit
	GLOBAL	getopt
	GLOBAL	_optarg
	GLOBAL	_opterr
	GLOBAL	_optind
	GLOBAL	_optopt
	GLOBAL	_optreset
	GLOBAL	l_bsearch
	GLOBAL	l_bsearch_callee
	GLOBAL	l_qsort
	GLOBAL	l_qsort_callee
	GLOBAL	qsort_sccz80
	GLOBAL	qsort_sccz80_callee
	GLOBAL	qsort_sdcc
	GLOBAL	qsort_sdcc_callee
	GLOBAL	_div_
	GLOBAL	_div__callee
	GLOBAL	_divu_
	GLOBAL	_divu__callee
	GLOBAL	_ldiv_
	GLOBAL	_ldiv__callee
	GLOBAL	_ldivu_
	GLOBAL	_ldivu__callee
	GLOBAL	abs
	GLOBAL	labs
	GLOBAL	isqrt
	GLOBAL	inp
	GLOBAL	outp
	GLOBAL	outp_callee
	GLOBAL	swapendian
	GLOBAL	bpoke
	GLOBAL	bpoke_callee
	GLOBAL	wpoke
	GLOBAL	wpoke_callee
	GLOBAL	bpeek
	GLOBAL	wpeek
	GLOBAL	t_delay
	GLOBAL	sleep
	GLOBAL	msleep
	GLOBAL	extract_bits
	GLOBAL	extract_bits_callee
	GLOBAL	wcmatch
	GLOBAL	unbcd
	GLOBAL	isalnum
	GLOBAL	isalpha
	GLOBAL	isascii
	GLOBAL	isbdigit
	GLOBAL	iscntrl
	GLOBAL	isdigit
	GLOBAL	isgraph
	GLOBAL	isupper
	GLOBAL	islower
	GLOBAL	isodigit
	GLOBAL	isoob
	GLOBAL	isprint
	GLOBAL	ispunct
	GLOBAL	isspace
	GLOBAL	isxdigit
	GLOBAL	toascii
	GLOBAL	tolower
	GLOBAL	toupper
	GLOBAL	bcmp
	GLOBAL	bcmp_callee
	GLOBAL	bcopy
	GLOBAL	bcopy_callee
	GLOBAL	bzero
	GLOBAL	bzero_callee
	GLOBAL	index
	GLOBAL	index_callee
	GLOBAL	rindex
	GLOBAL	rindex_callee
	GLOBAL	strset
	GLOBAL	strset_callee
	GLOBAL	strnset
	GLOBAL	strnset_callee
	GLOBAL	rawmemchr
	GLOBAL	rawmemchr_callee
	GLOBAL	_memlwr_
	GLOBAL	_memlwr__callee
	GLOBAL	_memstrcpy_
	GLOBAL	_memstrcpy__callee
	GLOBAL	_memupr_
	GLOBAL	_memupr__callee
	GLOBAL	_strrstrip_
	GLOBAL	ffs
	GLOBAL	ffsl
	GLOBAL	memccpy
	GLOBAL	memccpy_callee
	GLOBAL	memchr
	GLOBAL	memchr_callee
	GLOBAL	memcmp
	GLOBAL	memcmp_callee
	GLOBAL	memcpy
	GLOBAL	memcpy_callee
	GLOBAL	memmem
	GLOBAL	memmem_callee
	GLOBAL	memmove
	GLOBAL	memmove_callee
	GLOBAL	memrchr
	GLOBAL	memrchr_callee
	GLOBAL	memset
	GLOBAL	memset_callee
	GLOBAL	memswap
	GLOBAL	memswap_callee
	GLOBAL	stpcpy
	GLOBAL	stpcpy_callee
	GLOBAL	stpncpy
	GLOBAL	stpncpy_callee
	GLOBAL	strcasecmp
	GLOBAL	strcasecmp_callee
	GLOBAL	strcat
	GLOBAL	strcat_callee
	GLOBAL	strchr
	GLOBAL	strchr_callee
	GLOBAL	strchrnul
	GLOBAL	strchrnul_callee
	GLOBAL	strcmp
	GLOBAL	strcmp_callee
	GLOBAL	strcoll
	GLOBAL	strcoll_callee
	GLOBAL	strcpy
	GLOBAL	strcpy_callee
	GLOBAL	strcspn
	GLOBAL	strcspn_callee
	GLOBAL	strdup
	GLOBAL	strerror
	GLOBAL	stricmp
	GLOBAL	stricmp_callee
	GLOBAL	strlcat
	GLOBAL	strlcat_callee
	GLOBAL	strlcpy
	GLOBAL	strlcpy_callee
	GLOBAL	strlen
	GLOBAL	strlwr
	GLOBAL	strncasecmp
	GLOBAL	strncasecmp_callee
	GLOBAL	strncat
	GLOBAL	strncat_callee
	GLOBAL	strnchr
	GLOBAL	strnchr_callee
	GLOBAL	strncmp
	GLOBAL	strncmp_callee
	GLOBAL	strncpy
	GLOBAL	strncpy_callee
	GLOBAL	strndup
	GLOBAL	strndup_callee
	GLOBAL	strnicmp
	GLOBAL	strnicmp_callee
	GLOBAL	strnlen
	GLOBAL	strnlen_callee
	GLOBAL	strpbrk
	GLOBAL	strpbrk_callee
	GLOBAL	strrchr
	GLOBAL	strrchr_callee
	GLOBAL	strrcspn
	GLOBAL	strrcspn_callee
	GLOBAL	strrev
	GLOBAL	strrspn
	GLOBAL	strrspn_callee
	GLOBAL	strrstrip
	GLOBAL	strsep
	GLOBAL	strsep_callee
	GLOBAL	strspn
	GLOBAL	strspn_callee
	GLOBAL	strstr
	GLOBAL	strstr_callee
	GLOBAL	strstrip
	GLOBAL	strtok
	GLOBAL	strtok_callee
	GLOBAL	strtok_r
	GLOBAL	strtok_r_callee
	GLOBAL	strupr
	GLOBAL	strxfrm
	GLOBAL	strxfrm_callee
	GLOBAL	strrstr
	GLOBAL	strrstr_callee
	GLOBAL	memopi
	GLOBAL	memopi_callee
	GLOBAL	memopd
	GLOBAL	memopd_callee
	GLOBAL	__builtin_memset
	GLOBAL	__builtin_memcpy
	GLOBAL	__builtin_strcpy
	GLOBAL	__builtin_strchr
	GLOBAL	time
	GLOBAL	gmtime
	GLOBAL	localtime
	GLOBAL	mktime
	GLOBAL	asctime
	GLOBAL	ctime
	GLOBAL	clock
	GLOBAL	_FRAMES
	GLOBAL	bit_open
	GLOBAL	bit_open_di
	GLOBAL	bit_close
	GLOBAL	bit_close_ei
	GLOBAL	bit_click
	GLOBAL	bit_fx
	GLOBAL	bit_fx2
	GLOBAL	bit_fx3
	GLOBAL	bit_fx4
	GLOBAL	bit_fx5
	GLOBAL	bit_fx6
	GLOBAL	bit_fx7
	GLOBAL	bit_synth
	GLOBAL	bit_beep
	GLOBAL	bit_beep_callee
	GLOBAL	bit_noise
	GLOBAL	bit_noise_callee
	GLOBAL	patch_beep
	GLOBAL	patch_beep_callee
	GLOBAL	bit_frequency
	GLOBAL	bit_play
	GLOBAL	synth_phase
	GLOBAL	_synth_phase_1
	GLOBAL	_synth_phase_2
	GLOBAL	_synth_phase_3
	GLOBAL	_synth_phase_4
	GLOBAL	synth_play
	GLOBAL	buzzer_play
	GLOBAL	bksave
	GLOBAL	bkrestore
	GLOBAL	getsprite
	GLOBAL	putsprite
	GLOBAL	putsprite_callee
	GLOBAL	joystick
	GLOBAL	joystick_sc
	GLOBAL	kjoystick
	GLOBAL	_joystick_type
	GLOBAL	__x_proportional
	GLOBAL	__y_proportional
	GLOBAL	__xchar_proportional
	GLOBAL	__X_int1
	GLOBAL	__X_int2
	GLOBAL	__X_int3
	GLOBAL	__x_must_expose
	GLOBAL	XOpenDisplay
	GLOBAL	XCloseDisplay
	GLOBAL	DefaultScreen
	GLOBAL	RootWindow
	GLOBAL	XCreateSimpleWindow
	GLOBAL	XDestroyWindow
	GLOBAL	XCreateGC
	GLOBAL	XFreeGC
	GLOBAL	XDisplayName
	GLOBAL	DisplayWidth
	GLOBAL	DisplayHeight
	GLOBAL	DefaultDepth
	GLOBAL	BlackPixel
	GLOBAL	WhitePixel
	GLOBAL	XMapWindow
	GLOBAL	XSetForeground
	GLOBAL	XSetLineAttributes
	GLOBAL	XSetDashes
	GLOBAL	XSetStandardProperties
	GLOBAL	XSelectInput
	GLOBAL	XNextEvent
	GLOBAL	XCheckWindowEvent
	GLOBAL	XCheckTypedEvent
	GLOBAL	XFlush
	GLOBAL	XTextWidth
	GLOBAL	XLoadQueryFont
	GLOBAL	XDrawString
	GLOBAL	XUnloadFont
	GLOBAL	XSetFont
	GLOBAL	XCreateBitmapFromData
	GLOBAL	XDrawRectangle
	GLOBAL	XDrawPoint
	GLOBAL	XDrawLine
	GLOBAL	XClearWindow
	GLOBAL	_xfindchar
	GLOBAL	_xfputc
	GLOBAL	textcolor
	GLOBAL	textbackground
	GLOBAL	wherex
	GLOBAL	wherey
	GLOBAL	gotoxy
	GLOBAL	gotoxy_callee
	GLOBAL	screensize
	GLOBAL	screensize_callee
	GLOBAL	cprintf
	GLOBAL	cputs
	GLOBAL	cgets
	GLOBAL	kbhit
	GLOBAL	getch
	GLOBAL	cvpeek
	GLOBAL	cvpeekr
	GLOBAL	bordercolor
	GLOBAL	_ASCII
	GLOBAL	_vdp_writeReg
	GLOBAL	_vdp_getStat
	GLOBAL	_vdp_writeMemBlk
	GLOBAL	_vdp_getMemBlk
	GLOBAL	_vdp_setTextMode
	GLOBAL	_writeUlaReg
	GLOBAL	_textModeInit
	GLOBAL	_testMsg
	GLOBAL	_main


; --- End of Scope Defns ---


; --- End of Compilation ---
